services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    develop:
      watch:
        - action: sync
          path: ./static
          target: /usr/share/nginx/html